# Site settings
author: Sharon Watkins
title: Password Accepted
header-img: img/home-bg.png
email: swatkins876@gmail.com
copyright_name: Sharon Watkins
description: > # this means to ignore newlines until "baseurl:"
  A personal journey through learning tech.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SedX876
github_username:  sedx876

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
